version: '2.4'

services:

  zenoh:
    container_name: zenoh_go1_container
    image: eclipse/zenoh-bridge-ros2dds:1.8.0
    network_mode: "host"
#   restart: on-failure
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix:rw
#      - ~/.Xauthority:/root/.Xauthority:ro
#    tty: True
    environment:
      - ROS_DOMAIN_ID=3
      - ROS_DISTRO=humble
      - CYCLONEDDS_URI=/cyclonedds_config.xml
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp \
#      -  DISPLAY=${DISPLAY}
#      - XAUTHORITY=/root/.Xauthority

    volumes:
      -  ./entrypoint.sh:/entrypoint.sh
      -  ./cyclonedds_config.xml:/cyclonedds_config.xml
      -  ./zenoh_config_router_iot.json:/zenoh_config_router_iot.json
      -  ./zenoh_config_peer.json:/zenoh_config_peer.json
