
services:

  helios-kiss:
    container_name: helios16p_kiss-icp_container
    image: helios16p_kiss-icp_cyclone
    network_mode: "host"
    #restart: on-failure
    #volumes:
    #  - /tmp/.X11-unix:/tmp/.X11-unix:rw
    #  - ~/.Xauthority:/root/.Xauthority:ro
    #tty: True
    environment:
      -  ROS_DOMAIN_ID=3
      -  CYCLONEDDS_URI=/cyclonedds_config.xml
      -  RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      -  ROS_DISTRO=humble
    #  -  DISPLAY=${DISPLAY}
    #  -  XAUTHORITY=/root/.Xauthority

    volumes:
      -  ./entrypoint.sh:/entrypoint.sh
      -  ./cyclonedds_config.xml:/cyclonedds_config.xml

    entrypoint: /entrypoint.sh
