
services:

  helios-kiss:
    container_name: helios16p_kiss-icp_container
    image: helios16p_kiss-icp_cyclone
    network_mode: "host"
    #restart: on-failure
    #volumes:
    #  - /tmp/.X11-unix:/tmp/.X11-unix:rw
    #  - ~/.Xauthority:/root/.Xauthority:ro
    #tty: True
    environment:
      -  ROS_DOMAIN_ID=3   
      -  ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
    #  -  DISPLAY=${DISPLAY}
    #  -  XAUTHORITY=/root/.Xauthority

