/kiss_icp_node:
  ros__parameters:
    adaptive_threshold:
      initial_threshold: 2.0
      min_motion_th: 0.1
    base_frame: ''
    data:
      deskew: true
      max_range: 5.0
      min_range: 0.2
    invert_odom_tf: true
    lidar_odom_frame: odom_lidar
    mapping:
      max_points_per_voxel: 1
      voxel_size: 0.1
    orientation_covariance: 0.1
    position_covariance: 0.1
    publish_debug_clouds: false
    publish_odom_tf: true
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    registration:
      convergence_criterion: 0.0000000000000000001
      max_num_iterations: 700
      max_num_threads: 0
    use_sim_time: false

