version: '2.4'

services:

  zenoh:
    container_name: zenoh_client_container
    image: eclipse/zenoh-bridge-ros2dds:1.8.0
    network_mode: "host"
#   restart: on-failure
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix:rw
#      - ~/.Xauthority:/root/.Xauthority:ro
#    tty: True
    environment:
      - ROS_DOMAIN_ID=7
      - ROS_DISTRO=humble
      - ROS_LOCALHOST_ONLY=1 \
      - CYCLONEDDS_URI=/cyclonedds_config.xml
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp \
#      -  DISPLAY=${DISPLAY}
#      - XAUTHORITY=/root/.Xauthority

    volumes:
      -  ./entrypoint.sh:/entrypoint.sh
      -  ./cyclonedds_config.xml:/cyclonedds_config.xml
      -  ./zenoh_config_links_guest.json:/zenoh_config_links_guest.json
      -  ./zenoh_config_zeppelin.json:/zenoh_config_zeppelin.json
      -  ./zenoh_config_zeppelin.json:/zenoh_config_test_template.json
